const express = require("express")
const { protect,authorize } = require("../middleware/authMiddleware")
const {getCourses,getCoursesById,createCourses,deleteCourses,updateCourses} = require("../controllers/courseControllers")
const courseRoute = express.Router()
courseRoute.get("/", getCourses)
courseRoute.post("/",protect,authorize('instructor','student'), createCourses)
courseRoute.get("/:id", getCoursesById)
courseRoute.put("/:id", protect,authorize('instructor','admin'),updateCourses)
courseRoute.delete("/:id",deleteCourses)
module.exports = courseRoute